### ISSUE TITLE
Can't knit PRP-QUANT template

### ISSUE THREAD

**Issue by LisaSpitzerZPID** [crsh/prereg#22]
Hi @crsh,

I just tried to knit the PRP-QUANT template, but received the following error message:

Fehler: 'prp_quant_prereg' is not an exported object from 'namespace:prereg'
Ausführung angehalten

Do you know what the problem might be? Thank you in advance!

Best, Lisa

**Comment by crsh** [comment]
Hey @LisaSpitzerZPID, sorry, it seems the new function name was not exported because I had not rebuilt the `NAMESPACE` file. It should work now.

**Comment by LisaSpitzerZPID** [comment]
Yes, it works. Amazing - thank you!
